![rainbow](https://github.com/ancilcleetus/My-Learning-Journey/assets/25684256/839c3524-2a1d-4779-85a0-83c562e1e5e5)

# 1. Introduction to Data Computations with NumPy

Data science and machine learning often require efficient data handling and computations, especially when working with large datasets. NumPy, short for "Numerical Python," is a fundamental library for scientific computing in Python, providing powerful tools for handling arrays and matrices, along with an extensive collection of mathematical functions.

- **Why Use NumPy?**

    - **Efficient Data Storage:** NumPy arrays provide a highly efficient way to store large datasets in a contiguous block of memory, which makes them faster to process compared to Python lists.

    - **Vectorized Operations:** With NumPy, many operations can be performed directly on entire arrays, allowing for concise and optimized code that takes advantage of vectorized computation.

    - **Interoperability with Other Libraries:** NumPy is the foundation for other libraries like Pandas, SciPy, and TensorFlow, making it an essential skill for data scientists and machine learning practitioners.

    - **Extensive Mathematical Functions:** NumPy provides built-in functions for complex mathematical operations, like linear algebra, statistical analysis, Fourier transformations, and random sampling.
    
- **Topics Covered**

    - **Creating an Array in NumPy:** We’ll start by exploring different ways to create arrays in NumPy, including arrays of different dimensions, initialized with values or zeros, and special arrays for mathematical functions.

    - **Data Selection:** Indexing and Slicing of Arrays: Once we have arrays, we need to understand how to access and manipulate the data inside. This section covers essential techniques like indexing, slicing, and boolean indexing.

    - **Basic Array Operations:** NumPy makes performing element-wise and matrix operations straightforward. This section introduces addition, subtraction, multiplication, and division of arrays, as well as other common operations.

    - **Basic Statistics:** Statistical computations are fundamental to data analysis. Here, we’ll learn to compute metrics like mean, median, standard deviation, and other summary statistics directly on NumPy arrays.

    - **Data Manipulation:** Beyond basic operations, NumPy provides powerful tools for reshaping and transforming arrays to better suit specific data workflows, such as stacking arrays, reshaping dimensions, and transposing.
    
By the end of this notebook, you will have a solid foundation in using NumPy for data computations, equipping you to handle data more efficiently and to build more powerful analyses and models.

![rainbow](https://github.com/ancilcleetus/My-Learning-Journey/assets/25684256/839c3524-2a1d-4779-85a0-83c562e1e5e5)

# 2. Creating an array in NumPy

In [2]:
import numpy as np
from rich import print

Array can be a vector or a matrix or an n-dimensional array. A vector is a one dimensional array while a matrix is a two dimensional array.

In [11]:
# Create a vector => a one-dimensional array
vector = np.array([1, 2, 3, 4, 5])
print(f"Vector: {vector}")
print(f"type(vector): {type(vector)}")
print(f"Vector shape: {vector.shape}")
print(f"Vector dimension: {vector.ndim}")
print(f"Vector data type: {vector.dtype}")
print(f"Vector size: {vector.size}")

Vector: [1 2 3 4 5]

type(vector): <class 'numpy.ndarray'>

Vector shape: (5,)

Vector dimension: 1

Vector data type: int64

Vector size: 5

In [12]:
# Create a matrix => a two-dimensional array
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(f"Matrix: {matrix}")
print(f"type(matrix): {type(matrix)}")
print(f"Matrix shape: {matrix.shape}")
print(f"Matrix dimension: {matrix.ndim}")
print(f"Matrix data type: {matrix.dtype}")
print(f"Matrix size: {matrix.size}")

Matrix: [[1 2 3]
 [4 5 6]]

type(matrix): <class 'numpy.ndarray'>

Matrix shape: (2, 3)

Matrix dimension: 2

Matrix data type: int64

Matrix size: 6

In [13]:
# Create an array from a list
list = [1, 2, 3, 4, 5]
array = np.array(list)
print(f"Array: {array}")
print(f"type(array): {type(array)}")
print(f"Array shape: {array.shape}")
print(f"Array dimension: {array.ndim}")
print(f"Array data type: {array.dtype}")
print(f"Array size: {array.size}")

Array: [1 2 3 4 5]

type(array): <class 'numpy.ndarray'>

Array shape: (5,)

Array dimension: 1

Array data type: int64

Array size: 5

## Generating a NumPy array

NumPy offers various options to generate an array depending on different needs such as:

- Generating an identity array
- Generating an array of zeros of a given size
- Generating an array of ones of a given size
- Generating an array in a given range
- Generating an array with random values

### Generating an identity array

In [14]:
# Generating an identity array
identity_array = np.identity(4)
print(f"Identity array: {identity_array}")
print(f"type(identity_array): {type(identity_array)}")
print(f"Array shape: {identity_array.shape}")
print(f"Array dimension: {identity_array.ndim}")
print(f"Array data type: {identity_array.dtype}")
print(f"Array size: {identity_array.size}")

Identity array: [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

type(identity_array): <class 'numpy.ndarray'>

Array shape: (4, 4)

Array dimension: 2

Array data type: float64

Array size: 16

In [15]:
# Generating an identity array
identity_array = np.eye(4)
print(f"Identity array: {identity_array}")
print(f"type(identity_array): {type(identity_array)}")
print(f"Array shape: {identity_array.shape}")
print(f"Array dimension: {identity_array.ndim}")
print(f"Array data type: {identity_array.dtype}")
print(f"Array size: {identity_array.size}")

Identity array: [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

type(identity_array): <class 'numpy.ndarray'>

Array shape: (4, 4)

Array dimension: 2

Array data type: float64

Array size: 16

In [16]:
# You can multiply an identity array with any constant

print(np.eye(4) * 7)

[[7. 0. 0. 0.]
 [0. 7. 0. 0.]
 [0. 0. 7. 0.]
 [0. 0. 0. 7.]]

### Generating an array of zeros of a given size

In [18]:
# Generating a one-dimensional array of zeros
zeros_array = np.zeros(5)
print(f"Zeros array: {zeros_array}")
print(f"type(zeros_array): {type(zeros_array)}")
print(f"Array shape: {zeros_array.shape}")
print(f"Array dimension: {zeros_array.ndim}")
print(f"Array data type: {zeros_array.dtype}")
print(f"Array size: {zeros_array.size}")

Zeros array: [0. 0. 0. 0. 0.]

type(zeros_array): <class 'numpy.ndarray'>

Array shape: (5,)

Array dimension: 1

Array data type: float64

Array size: 5

In [19]:
# Generating a two-dimensional array of zeros
zeros_array = np.zeros((2, 3))
print(f"Zeros array: {zeros_array}")
print(f"type(zeros_array): {type(zeros_array)}")
print(f"Array shape: {zeros_array.shape}")
print(f"Array dimension: {zeros_array.ndim}")
print(f"Array data type: {zeros_array.dtype}")
print(f"Array size: {zeros_array.size}")

Zeros array: [[0. 0. 0.]
 [0. 0. 0.]]

type(zeros_array): <class 'numpy.ndarray'>

Array shape: (2, 3)

Array dimension: 2

Array data type: float64

Array size: 6

### Generating an array of ones of a given size

In [20]:
# Generating a one-dimensional array of ones
ones_array = np.ones(5)
print(f"Ones array: {ones_array}")
print(f"type(ones_array): {type(ones_array)}")
print(f"Array shape: {ones_array.shape}")
print(f"Array dimension: {ones_array.ndim}")
print(f"Array data type: {ones_array.dtype}")
print(f"Array size: {ones_array.size}")

Ones array: [1. 1. 1. 1. 1.]

type(ones_array): <class 'numpy.ndarray'>

Array shape: (5,)

Array dimension: 1

Array data type: float64

Array size: 5

In [21]:
# Generating a two-dimensional array of ones
ones_array = np.ones((2, 3))
print(f"Ones array: {ones_array}")
print(f"type(ones_array): {type(ones_array)}")
print(f"Array shape: {ones_array.shape}")
print(f"Array dimension: {ones_array.ndim}")
print(f"Array data type: {ones_array.dtype}")
print(f"Array size: {ones_array.size}")

Ones array: [[1. 1. 1.]
 [1. 1. 1.]]

type(ones_array): <class 'numpy.ndarray'>

Array shape: (2, 3)

Array dimension: 2

Array data type: float64

Array size: 6

### Generating an array in a given range

In [22]:
# Generating an array in a given range or interval
range_array = np.arange(10)
print(f"Range array: {range_array}")

Range array: [0 1 2 3 4 5 6 7 8 9]

In [23]:
# If you want to control the step size
range_array = np.arange(0, 10, 2)
print(f"Range array: {range_array}")

Range array: [0 2 4 6 8]

In [25]:
# Use linspace to generate evenly spaced numbers in a given interval
linspace_array_01 = np.linspace(0, 1, 5)
print(f"linspace_array_01: {linspace_array_01}")

linspace_array_02 = np.linspace(0, 10, 5)
print(f"linspace_array_02: {linspace_array_02}")

linspace_array_03 = np.linspace(0, 10, 5, endpoint=False)
print(f"linspace_array_03: {linspace_array_03}")

linspace_array_04, step = np.linspace(0, 10, 5, retstep=True)
print(f"linspace_array_04: {linspace_array_04}")
print(f"step: {step}")

linspace_array_05 = np.linspace(0, 10, 10)
print(f"linspace_array_05: {linspace_array_05}")

linspace_array_01: [0.   0.25 0.5  0.75 1.  ]

linspace_array_02: [ 0.   2.5  5.   7.5 10. ]

linspace_array_03: [0. 2. 4. 6. 8.]

linspace_array_04: [ 0.   2.5  5.   7.5 10. ]

step: 2.5

linspace_array_05: [ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]

### Generating an array with random values

In [27]:
# Create a 1D array with 4 random numbers
random_array = np.random.rand(4)
print(f"Random array: {random_array}")

# Will not get the same values
random_array = np.random.rand(4)
print(f"Random array: {random_array}")

# Will not get the same values
random_array = np.random.rand(4)
print(f"Random array: {random_array}")

Random array: [0.04466843 0.95668582 0.16456498 0.54350351]

Random array: [0.07962073 0.29062389 0.09010576 0.2652263 ]

Random array: [0.78042007 0.68995679 0.97842591 0.52874568]

In [28]:
# Create a 2D array with 4 * 5 random numbers
random_array = np.random.rand(4, 5)
print(f"Random array: {random_array}")

Random array: [[0.81562118 0.79647115 0.20177386 0.38521962 0.26566251]
 [0.4773823  0.37114683 0.58031272 0.27881591 0.50774572]
 [0.23354136 0.22815491 0.11037669 0.27336011 0.30590957]
 [0.20457511 0.72212715 0.35406106 0.2913753  0.29373487]]

In [29]:
# Generate one random integer in a given range
random_integer = np.random.randint(5, 50)
print(f"Random integer: {random_integer}")

Random integer: 15

In [30]:
# Generate 10 random integers in a given range
random_integers = np.random.randint(5, 50, 10)
print(f"Random integers: {random_integers}")

Random integers: [33 24  8 40 31 33 18 32 34 14]

In [32]:
# Make random numbers reproducible

# Set the random seed
np.random.seed(42)  # You can replace 42 with any integer

# Generate random numbers
random_array = np.random.rand(4)
print(f"Random array: {random_array}")

np.random.seed(42)

# Generate random numbers again
random_array = np.random.rand(4)
print(f"Random array: {random_array}")

np.random.seed(42)

# Generate random numbers again
random_array = np.random.rand(4)
print(f"Random array: {random_array}")

Random array: [0.37454012 0.95071431 0.73199394 0.59865848]

Random array: [0.37454012 0.95071431 0.73199394 0.59865848]

Random array: [0.37454012 0.95071431 0.73199394 0.59865848]

![rainbow](https://github.com/ancilcleetus/My-Learning-Journey/assets/25684256/839c3524-2a1d-4779-85a0-83c562e1e5e5)

# 3. Data Selection: Indexing and Slicing a NumPy Array

- **Indexing:** Selecting individual elements from the array

- **Slicing:** Selecting a group of elements from the array

## 1D Array Indexing and Slicing

In [35]:
# Creating a 1 dimensional vector
array_1d = np.array([1,2,3,4,5])
print(f"array_1d: {array_1d}")
print("\n")

# Indexing: selcting an element from an array
print(f"array_1d[0]: {array_1d[0]}")
print(f"array_1d[1]: {array_1d[1]}")
print(f"array_1d[-1]: {array_1d[-1]}")
print("\n")

# Slicing: selecting a group of elements from an array
print(f"array_1d[1:3]: {array_1d[1:3]}")
print(f"array_1d[2:]: {array_1d[2:]}")
print(f"array_1d[:3]: {array_1d[:3]}")

array_1d: [1 2 3 4 5]

array_1d[0]: 1

array_1d[1]: 2

array_1d[-1]: 5

array_1d[1:3]: [2 3]

array_1d[2:]: [3 4 5]

array_1d[:3]: [1 2 3]

## 2D Array Indexing and Slicing

In [36]:
# Creating a 2D array
array_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"array_2d: {array_2d}")

array_2d: [[1 2 3]
 [4 5 6]
 [7 8 9]]

In [41]:
# Indexing: selcting an element from an array
# array_2d[row][column]

# Let's select 5; i.e. row 1, column 1 (we start from 0!!)
print(f"array_2d[1][1]: {array_2d[1][1]}")
print("\n")

# Let's select 8; i.e. row 2, column 1
print(f"array_2d[2][1]: {array_2d[2][1]}")

array_2d[1][1]: 5

array_2d[2][1]: 8

In [49]:
# Slicing: selecting a group of elements from an array

# Selecting whole row
# array_2d[row] or array_2d[row, :]
# Let's select 2nd row i.e row 1
print(f"2nd row => array_2d[1]: {array_2d[1]}")
# Let's select 1st row i.e row 0
print(f"1st row => array_2d[0, :]: {array_2d[0, :]}")
print("\n")

# Selecting whole column
# array_2d[:,column]
# Let's select 2nd column i.e column 1
print(f"2nd column => array_2d[:, 1]: {array_2d[:,1]}")
# Let's select 1st column i.e column 0
print(f"1st column => array_2d[:, 0]: {array_2d[:, 0]}")
print("\n")

# Selecting a group of elements in 2D array
# array_2d[rows, columns]

# Let's select the first two rows
print(f"first two rows => array_2d[:2]: {array_2d[:2]}")
print("\n")

# Let's select the first two columns
print(f"first two columns => array_2d[:, :2]: {array_2d[:, :2]}")
print("\n")

# Let's select the last two rows
print(f"last two rows => array_2d[1:3]: {array_2d[1:3]}")
print("\n")

# Let's select the last two columns
print(f"last two columns => array_2d[:, 1:3]: {array_2d[:, 1:3]}")
print("\n")

# Let's select the first two rows and first two columns
print(f"first two rows and first two columns => array_2d[:2, :2]: {array_2d[:2, :2]}")
print("\n")

# Let's select the last two rows and last two columns
print(f"last two rows and last two columns => array_2d[1:3, 1:3]: {array_2d[1:3, 1:3]}")
print("\n")

# Let's select the first two rows and last two columns
print(f"first two rows and last two columns => array_2d[:2, 1:3]: {array_2d[:2, 1:3]}")
print("\n")

# Let's select the last two rows and first two columns
print(f"last two rows and first two columns => array_2d[1:3, :2]: {array_2d[1:3, :2]}")
print("\n")

# Let's select the entire array
# array_2d[:] or array_2d[:, :]
print(f"entire array => array_2d[:]: {array_2d[:,:]}")
print(f"entire array => array_2d[:, :]: {array_2d[:,:]}")

2nd row => array_2d[1]: [4 5 6]

1st row => array_2d[0, :]: [1 2 3]

2nd column => array_2d[:, 1]: [2 5 8]

1st column => array_2d[:, 0]: [1 4 7]

first two rows => array_2d[:2]: [[1 2 3]
 [4 5 6]]

first two columns => array_2d[:, :2]: [[1 2]
 [4 5]
 [7 8]]

last two rows => array_2d[1:3]: [[4 5 6]
 [7 8 9]]

last two columns => array_2d[:, 1:3]: [[2 3]
 [5 6]
 [8 9]]

first two rows and first two columns => array_2d[:2, :2]: [[1 2]
 [4 5]]

last two rows and last two columns => array_2d[1:3, 1:3]: [[5 6]
 [8 9]]

first two rows and last two columns => array_2d[:2, 1:3]: [[2 3]
 [5 6]]

last two rows and first two columns => array_2d[1:3, :2]: [[4 5]
 [7 8]]

entire array => array_2d[:]: [[1 2 3]
 [4 5 6]
 [7 8 9]]

entire array => array_2d[:, :]: [[1 2 3]
 [4 5 6]
 [7 8 9]]

![rainbow](https://github.com/ancilcleetus/My-Learning-Journey/assets/25684256/839c3524-2a1d-4779-85a0-83c562e1e5e5)

In [ ]:
# Deep Learning as subset of ML

from IPython import display
display.Image("data/images/01-Deep-Learning-Foundations/CampusX-Deep-Learning-Course/DL_01_Intro-01-DL-subset-of-ML.jpg")

![rainbow](https://github.com/ancilcleetus/My-Learning-Journey/assets/25684256/839c3524-2a1d-4779-85a0-83c562e1e5e5)