![rainbow](https://github.com/ancilcleetus/My-Learning-Journey/assets/25684256/839c3524-2a1d-4779-85a0-83c562e1e5e5)

# 1. Tensors in PyTorch

Tensors are a fundamental data structure used in the field of machine learning and scientific computing. At their core, tensors are multi-dimensional arrays. Tensors efficiently store and manipulate the complex, multidimensional data used in machine learning models.

In [1]:
import torch

- Scalar $\implies$ 1st order tensor
- Vector $\implies$ 2nd order tensor
- Matrix $\implies$ 3rd order tensor

Let's see a few basic tensor manipulations.

## 1. Create tensors

A few of the ways to create tensors are given below:

In [2]:
# Using a List

lst = list(range(10))
print(f"List: {lst}")

a = torch.tensor(lst)
print(f"Torch Tensor: {a}")

List: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Torch Tensor: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [3]:
# Creating a 2D tensor (matrix)
tensor_2d = torch.tensor([[1, 2, 3],
                          [4, 5, 6]])

# Creating a 3D tensor
tensor_3d = torch.tensor([[[1, 2, 3],
                           [4, 5, 6]],
                          [[7, 8, 9],
                           [10, 11, 12]]])

# Creating a 4D tensor
tensor_4d = torch.tensor([[[[1, 2],
                            [3, 4]],
                           [[5, 6],
                            [7, 8]]],
                          [[[9, 10],
                            [11, 12]],
                           [[13, 14],
                            [15, 16]]]])

# Print the tensors
print(f"2D Tensor (Matrix): \n{tensor_2d}")
print(f"Shape: {tensor_2d.shape}")
print("\n")

print(f"3D Tensor (Matrix): \n{tensor_3d}")
print(f"Shape: {tensor_3d.shape}")
print("\n")

print(f"4D Tensor (Matrix): \n{tensor_4d}")
print(f"Shape: {tensor_4d.shape}")
print("\n")

2D Tensor (Matrix): 
tensor([[1, 2, 3],
        [4, 5, 6]])
Shape: torch.Size([2, 3])


3D Tensor (Matrix): 
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
Shape: torch.Size([2, 2, 3])


4D Tensor (Matrix): 
tensor([[[[ 1,  2],
          [ 3,  4]],

         [[ 5,  6],
          [ 7,  8]]],


        [[[ 9, 10],
          [11, 12]],

         [[13, 14],
          [15, 16]]]])
Shape: torch.Size([2, 2, 2, 2])




In [5]:
print(f"Tensor Type: {tensor_2d.dtype}")
print(f"Tensor Device: {tensor_2d.device}")

Tensor Type: torch.int64
Tensor Device: cpu


In [6]:
# Using a Numpy Array
import numpy as np

np_array = np.array(list(range(10)))
print(f"Numpy array: {np_array} || datatype: {type(np_array)}")

# Convert NumPy array to PyTorch tensor
torch_tensor = torch.tensor(np_array)
# or
torch_tensor = torch.from_numpy(np_array)
print(f"Torch Tensor: {torch_tensor} || datatype: {type(torch_tensor)}")

# Convert tensor to numpy array
c = torch_tensor.numpy()
print(f"Numpy array: {c} || datatype: {type(c)}")

Numpy array: [0 1 2 3 4 5 6 7 8 9] || datatype: <class 'numpy.ndarray'>
Torch Tensor: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) || datatype: <class 'torch.Tensor'>
Numpy array: [0 1 2 3 4 5 6 7 8 9] || datatype: <class 'numpy.ndarray'>


In [7]:
# We cannot create a tensor using a hashmap
hashmap = {1:1,2:2,3:3}
print(f"Datatype: {type(hashmap)}")
print(torch.tensor(hashmap))

Datatype: <class 'dict'>


RuntimeError: Could not infer dtype of dict

In [8]:
# We cannot create a tensor using a hashset
hashset = set([1,22,3,5,6,4,8])
print(f"Datatype: {type(hashset)}")
print(torch.tensor(hashset))

Datatype: <class 'set'>


RuntimeError: Could not infer dtype of set

In [10]:
# We cannot create a tensor using a non-uniform tuple
tup_non_uniform = tuple([("a",2),("b",4),("c",6)])
print(f"Datatype: {type(tup_non_uniform)}")
print(torch.tensor(tup_non_uniform))

Datatype: <class 'tuple'>


ValueError: too many dimensions 'str'

In [12]:
# We can create a tensor using a uniform tuple
tup_uniform = tuple([(1,2),(2,4),(3,6)])
print(f"Datatype: {type(tup_uniform)}")
print(torch.tensor(tup_uniform))

Datatype: <class 'tuple'>
tensor([[1, 2],
        [2, 4],
        [3, 6]])


In [13]:
z = torch.zeros((5, 3))
print(f"z = \n{z}")
print(f"Datatype: {z.dtype}")

z = 
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
Datatype: torch.float32


Above, we create a 5x3 matrix filled with zeros. The zeros are 32-bit floating point numbers which is the default in PyTorch.

We can change the default datatype as well.

In [14]:
i = torch.ones((5, 3), dtype=torch.int16)
print(f"i = \n{i}")
print(f"Datatype: {i.dtype}")

i = 
tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
Datatype: torch.int16


![rainbow](https://github.com/ancilcleetus/My-Learning-Journey/assets/25684256/839c3524-2a1d-4779-85a0-83c562e1e5e5)

In [ ]:
# Deep Learning as subset of ML

from IPython import display
display.Image("data/images/DL_01_Intro-01-DL-subset-of-ML.jpg")

![rainbow](https://github.com/ancilcleetus/My-Learning-Journey/assets/25684256/839c3524-2a1d-4779-85a0-83c562e1e5e5)